@extends('dashboard.layouts.app')
@section('content')
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12" style="padding: 20px; background-color: white; border-radius: 10px;">
                                <div class="page-title-box justify-content-between">
                                    <p style="text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><u><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">DISCLAIMER</span></span></u></strong></span></span></p>

                                    <p style="text-align:justify">&nbsp;</p>
                                    
                                    <p style="margin-left:6px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><u><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Acceptance</span></span></u></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: Your relationship with the us shall be governed by this <strong>Disclaimer</strong>, and our <strong>Terms &amp; Conditions, Community <span style="color:black">Guidelines,</span></strong><span style="color:black"> <strong>Cookie Policy</strong> and <strong>Privacy Policy</strong> statement displayed on the Site. By accessing and/or using our platform, you accept and agree with this <strong>Disclaimer</strong>, and all our terms and conditions as applicable to you.</span></span></span></span></span></p>
                                    
                                    <p style="margin-left:6px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><u><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:black">Disclaimer</span></span></span></u></strong><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:black">:</span></span></span></strong></span></span></p>
                                    
                                    <ol style="list-style-type:lower-alpha">
                                    	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:black">The prices of the currencies, commodities and any other items displayed on the dashboard are for informational purposes only. We take reasonable endeavors to ensure that their prices are updated every 10 minutes, but we cannot rule out the situations where these aren&rsquo;t updated for certain reasons. Therefore, Recycling Market News does not guarantee the timeliness, update, accuracy, adequacy, reliability or completeness of such information in respect to the prices of the currencies and commodities, and we are not responsible for any errors or omissions or delay in updating or for the results or losses obtained or suffered from the use of any such information in any manner whatsoever. We encourage all users to use the information on the site as a resource only to further their own research. Nothing published on this site should be considered as investment advice.</span></span></span></span></span></li>
                                    	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"><span style="color:black">While using our Site, and our services, you may encounter content (such as news headlines, magazines, news or comments) and links that belong to third party news agencies or independent news publishers/recyclers or general users of the Site. Therefore, there is a likelihood that such </span></span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">information or content could be inaccurate, incomplete, delayed, misleading, illegal, offensive or otherwise harmful. Recycling Market News generally does not review content requested to be published by such third-party news agencies. Similarly, while we reserve the right to scrutinize the validity or authenticity of any news sought to be published by news publishers/recyclers, we expressly disclaim any and all warranties in this respect. To be more specific, we disclaim that any news or content that you will find on our platform will always be trustworthy, non-misleading and complete. We cannot always prevent this misuse of our Services. Therefore, you agree that we are only an intermediary platform, and are not liable or responsible for such content or information. As a user, you are free to leave a comment to start a healthy debate on any the news content that you find on our Site, while ensuring the same complies with our <strong>Community Guidelines</strong> at all times.</span></span></span></span></li>
                                    	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We expressly disclaim any warranty in respect of our services, and do not guarantee that our Site will bring traffic to your Site, or that you will find information or content posted on our Site a useful. We do not control the ratings left by the users to your profile as a news publisher/recycler.</span></span></span></span></li>
                                    	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We are only an intermediary platform that publishes the news headlines and magazines of third-party news agency, and the news of the independent publisher/recycler. You acknowledge and undertake that you are accessing the services on the platform and transacting at your own risk and are using your best and prudent judgment before entering into any such transactions with such news agencies or before relying upon the content posted by publisher/recycler. </span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We do not verify the authenticity of any of the news or content. We shall neither be liable nor responsible for any actions or inactions of either the news reader or the news agencies or the news publishers/recyclers. </span></span><strong><em><u><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We shall not mediate or resolve or be a party to any dispute or disagreement between the you and any of the news agencies or publishers/recyclers.</span></span></u></em></strong></span></span></li>
                                    	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The <span style="color:black">Site, information present on the site and all its services are provided on an <strong>&ldquo;as-is&rdquo;</strong> basis, and Recycling Market News (and our licensors and affiliates) expressly disclaims any and all warranties and conditions of any kind, whether express, implied, or statutory, including all warranties or conditions of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, title, quiet enjoyment, accuracy, or non-infringement. We make no warranty that the Site or prices of currencies &amp; commodities or services or news or comments or its content will meet your requirements, will be available on an uninterrupted, timely, secure, or error-free basis, or will be accurate, reliable, free of viruses or other harmful code, complete, legal, or safe. All risks associated with trading using any of the information present on the Site lies with the users/investors alone.</span></span></span></span></span></li>
                                    </ol>
                                    
                                    <p style="text-align:justify">&nbsp;</p>
                                    
                                    <p style="margin-left:6px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Contact Us: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">For any query or assistance, please write us at </span></span><a href="mailto:info@recyclingmarketnews.com" style="color:blue; text-decoration:underline"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">info@recyclingmarketnews.com</span></span></a></span></span></p>
                                    
                                    <p style="text-align:justify">&nbsp;</p>

                                </div>
                            </div>
                        </div>
                    <!-- end page title -->

                        <div class="row">
                            <div class="col-xl-12">
    
                            </div>
                        </div>
                    </div>
                </div> <!-- container-fluid -->
            </div>
            <!-- End Page-content -->
@endsection
