<?php $__env->startSection('content'); ?>
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="main-content">

                <div class="page-content">
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            
                            <div class="col-12" style="padding: 20px; background-color: white; border-radius: 10px;">
                                <div class="page-title-box justify-content-between">
                                   <p style="text-align:center"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><u><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">TERMS &amp; CONDITIONS</span></span></u></strong></span></span></p>

<p style="text-align:justify">&nbsp;</p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">These <strong>Terms &amp; Conditions</strong> (hereinafter referred to as the <strong>&ldquo;Terms&rdquo; </strong>or <strong>&ldquo;Terms of Use&rdquo;</strong>) shall govern the relationship between <strong>Global Recycling Market LTD</strong>, and having its registered office at <strong>71-75 Shelton Street Covent Garden London, WC2H 9JQ, UNITED KINGDOM </strong>(hereinafter referred to the <strong>&ldquo;Company&rdquo;</strong> or <strong>&ldquo;Recycling Market News&rdquo;</strong> or <strong>&ldquo;us&rdquo;</strong> or <strong>&ldquo;our&rdquo;</strong> or <strong>&ldquo;we&rdquo;</strong>) and you (hereinafter referred to <strong>&ldquo;you&rdquo;</strong> or <strong>&ldquo;your&rdquo;</strong> or <strong>&ldquo;user(s)&rdquo; </strong>or <strong>&ldquo;reader(s)&rdquo; </strong>or <strong>&ldquo;news agency&rdquo;</strong>) and shall also govern your use of </span></span><a href="http://www.recyclingmarketnews.com/" style="color:#0563c1; text-decoration:underline"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">www.recyclingmarketnews.com/</span></span></a><strong> </strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">(hereinafter referred to as the <strong>&ldquo;Website&rdquo;</strong> or <strong>&ldquo;Site&rdquo;</strong>).</span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Additionally, how we collect, use, store, share and transmit your data is governed by our <strong>Privacy Policy</strong> statement and <strong>Cookie Policy</strong>. These <strong>Terms &amp; Conditions</strong> shall be read in conjunction with our <strong>Disclaimer, Community Guidelines, Refund Policy</strong>, <strong>Privacy Policy</strong> statement, and <strong>Cookie Policy</strong>. </span></span></span></span></p>

<p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">If you do not accept these Terms in its entirety, then you cannot use the site or avail our services.</span></span></span></span></p>

<ol>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">ACCEPTANCE OF THE TERMS &amp; CONDITIONS</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">By accessing or using our Website or purchasing a subscription or becoming a news publisher on our platform or contacting us in any way or by clicking on a button or taking similar action to signify your affirmative acceptance of these Terms, you hereby represent that:</span></span></span></span></p>

<ol style="list-style-type:lower-roman">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You have read, understood, and agreed to be bound by these Terms, any future updates and additions to these Terms, as published from time to time at the Website.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You are of <strong>sound mind</strong> and at least of the <strong>age of majority</strong> as per the laws of State that you reside in, in order to form a binding contract with us. <u>In case you are not of the age of majority, then you must have the permission of your lawful guardian to use and access the Website.</u></span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You have read, understood and consented to our <strong>Disclaimer, Community Guidelines, Refund Policy</strong>, <strong>Privacy Policy</strong> statement and <strong>Cookie Policy</strong>.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We have not previously disabled your account for the violation of law or any of our policies.</span></span></span></span></li>
</ol>

<p style="margin-left:96px; text-align:justify">&nbsp;</p>

<ol start="2">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">ACCOUNTS, PASSWORDS AND SECURITY</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt">Account Registration:</span></strong><strong><span style="font-size:10.0pt"> To access various parts of the Website, and to avail various services of Recycling Market News</span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">, <strong>you might be required to register and create an account with us. </strong>When setting up and maintaining your account, you must provide and continue to provide accurate and complete information about yourself. </span></span><a href="https://www.lawinsider.com/clause/account-password-and-security" style="color:#0563c1; text-decoration:underline"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">As part</span></span></a><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> of the registration process, you will create a password and an account. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Security:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> You are responsible for maintaining the confidentiality of the password and account, and are fully responsible for all activities that occur under your account, including, without limitation, all actions by sub-users registered under your account. You agree to (a) immediately notify us of any unauthorized use of your password or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session. We cannot and will not be liable for any loss, damage or other liability arising from your failure to comply with this Section or from any unauthorized access to or use of your account.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Inaccurate Information:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> If we have reasonable grounds to suspect that any of the information submitted by you is untrue, inaccurate, outdated, or incomplete, we may terminate your account and refuse current or future use of any or all of the services.</span></span></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="3">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">USE OF THE SITE</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-roman">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Allowed uses:</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Directions of Use:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> You must follow any and all guidelines or policies or directions of use as associated with our services, including all the features and functionalities of our Website. If you are contributing as a news publisher on our platform, or if you are a reader who wants to leave a comment on any content on the platform, you must comply with our <strong>Community Guidelines </strong>as posted on our Site.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Information:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Whenever prompted, you must provide us with the correct, accurate and updated information about yourself.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Material:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> For the purposes of these Terms, &ldquo;material&rdquo; shall mean any video, text, news, graphics, sound material, published on the Website, whether a copyright of Recycling Market News, news publisher, news agency, its licensors or other users or any third party. You are not allowed to download or print the material, or extracts from it, in a systematic or regular manner or otherwise so as to create a database in electronic or paper form comprising all or part of the material appearing on the Website. You must not reproduce any part of the Website or the material or transmit it to or store it in any other website or disseminate any part of the material in any other form, <em>unless we have indicated that you may do so</em>.</span></span></span></span></li>
</ol>

<p style="margin-left:144px; text-align:justify">&nbsp;</p>

<ol start="2" style="list-style-type:lower-roman">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Restricted uses:</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You can&rsquo;t impersonate others or provide inaccurate information or publish a false or misleading content. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You must not misuse or interfere with the Website or our services or try to access them using a method other than the interface and the instructions that we provide. You may use the services only as permitted by applicable law, and as per the directions provided by us. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You must not:</span></span></span></span></li>
</ol>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">republish material from the Website;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">sell, rent or sub-license material from the Website;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">show any material from the Website in public without our consent;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">edit or otherwise modify any material on the Website (other than editing your own information as per the method provided);</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">reproduce, duplicate, copy or otherwise exploit material on our Website for a commercial purpose; or</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">redistribute material from the Website, except for content specifically and expressly made available for redistribution, or with our written consent and according to our terms;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">infringe or violate our Intellectual Property Rights or Intellectual Property Rights of our licensors or other users or any third party;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We reserve the right to restrict your access to any areas of our Website, or indeed our whole Website, at our discretion.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We reserve the right to discontinue our services, or discontinue any of the Website features, at any time, at our sole discretion.</span></span></span></span></li>
</ul>

<ol start="4" style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You must not use our Website in any way that causes, or may cause, damage to the Website or impairment of the availability or accessibility of the Website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You must not use our Website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, trojan horse, worm, keystroke logger, rootkit or other malicious computer software.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You must not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to our Website, without our express written consent.</span></span></span></span></li>
</ol>

<p style="text-align:justify">&nbsp;</p>

<ol start="4">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">NEWS PUBLISHER </span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Become a Publisher</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: On Recycling Market News, you have the opportunity and an option to become a contributor in form of news publisher, and publish the news relating to theme of our platform. Please note, whenever you submit such a news or content for publishing on our platform, the same is subject to our approval, and it will go via our back-end analysts and managers for approval.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Disclaimer of Warranty:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> While we reserve the right to scrutinize the validity or authenticity of such news and content, we expressly disclaim any and all warranties in this respect. To be more specific, we disclaim that any news or content that you will find on our platform will always be trustworthy, non-misleading and complete. Therefore, we disclaim all liabilities in this respect. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Right of Modification:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> We also reserve the right to publish such news or content after modifying or adding to it, if we deem it necessary, in our sole discretion. Your only right as a news publisher against this act will be to remove your news/content, or request us to modify it. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Community Guidelines:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> There will be a public comment section on each news so that users can come and comment, and/or start a debate, in respect to the content of the news. All the users, as well as news publishers are required to comply with our Community Guidelines while leaving any comment or replying to such comments. Any news, content, or comment that will violate the Community Guidelines, can and will be deleted, at our sole discretion. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Rating System:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> We want to create our platform a trustworthy one, which is why we also allow general users and readers of the Site to rate the news publishers on authenticity and sense on each news that they publish. On the publisher profile, these star rating system <em>(from 0 to 5)</em> will be publicly visible to all the users and visitors of the Site. &nbsp;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Dishonest means</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: As a news publisher, you cannot control what other users will rate you or say about you. You are also expressly prohibited from engaging any unlawful or dishonest or paid means of affecting your ratings or the ratings of any other news publisher. &nbsp;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Connect:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> We will give a style connect option to the users to connect with their favorite recyclers/publishers, so that these users are able to receive a notification each time such recyclers/publishers publish the news, just to stay within their network. </span></span></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="5">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">OUR CONTENT AND RIGHTS</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">This Website, its logos, its content, news headlines, designs, trademarks, trade dress, trade name, all of our features, functionalities and services, shall remain the sole property of the Recycling Market News, and/or its licensors, as the case may be. Your use of or access to this Website or availing of our services shall not in any way transfer or assign to you any ownership or other proprietary rights in or to this Website, our services, any content <em>(except your own content)</em>, designs, published by us or our licensors or third parties. This Website and the content, including but not limited to the trademark, logo, copyright, design, layout, typography, underlying HTML, Java scripts, text, audio clips, video clips and graphics, and in the expression of the information contained herein, whether as a compilation or otherwise is protected by relevant Intellectual Property laws, rules and regulations. Trademarks, trade names and designs appearing on this Website are the exclusive property of, or are licensed to the Recycling Market News and are protected.<strong> No use of a trademark, trade dress, trade name, content or design appearing on this Website may be made without the prior written permission of the Recycling Market News.</strong></span></span></span></span></p>

<p style="margin-left:120px; text-align:justify">&nbsp;</p>

<ol start="6">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">YOUR CONTENT AND RIGHTS AS A PUBLISHER/RECYCLER</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Your Content:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> As a publisher/recycler, you are entitled to post news about the theme of the platform and share it with the users and other readers of the Site. This content of yours may be protected by intellectual property laws. You own the intellectual property rights in any and all such content. Nothing in these Terms takes away the rights you have to your own content or news. You are free to share your content (except defamatory one) with anyone else, wherever you want.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">License:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp; However, to provide our services we need you to give us some legal permissions (known as a &lsquo;license&rsquo;) to use this news/content of yours. This is solely for the purposes of providing and improving our services.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Description of License</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: Specifically, when we approve and post your news on our Site, you grant us a non-exclusive, transferable, sub-licensable, royalty-free, and worldwide license to host, use, publish, distribute, modify, copy, publicly perform or display, and translate your content on our Website. However, we might take down this content of yours if we, in good-faith, believe to be violative of our policies or any third-party rights. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Advertisements:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> We will not include your content in advertisements for the products and services of third parties to others without your separate consent. However, we have the right, without payment to you or others, to serve ads near your content and information. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You may share it with others:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Since you own your content and information and we only have non-exclusive rights to it, you may choose to make it available to others, at your sole discretion.</span></span></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="7">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">RIGHTS IN COMMENTS POSTED AS A USER</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Comments:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> As a general user or reader of the Site, you are entitled to post your comments on the news and some other content that you find on the platform. This comment of yours may be protected by intellectual property laws. You own the intellectual property rights in any and all such comment. Nothing in these Terms takes away the rights you have to your own comment. You are free to share your comment (except defamatory one) with anyone else, wherever you want.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">License:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp; However, to provide our services we need you to give us some legal permissions (known as a &lsquo;license&rsquo;) to use this comment of yours. This is solely for the purposes of providing and improving our services.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Description of License</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: Specifically, when you post a comment on the Site, you grant us a non-exclusive, transferable, sub-licensable, royalty-free, and worldwide license to host, use, publish, distribute, modify, copy, publicly perform or display, and translate your content on our Website. However, we might take down this comment of yours if we, in good-faith, believe to be violative of our policies or any third-party rights. </span></span></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="8">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">YOUR CONTENT AND RIGHTS AS A NEWS AGENCY</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Your Content:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Depending upon the package purchased by you, </span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">we will copy a certain number of your news headlines each month as per agreement between us, and will publish the same on our website. However, you also have an option to inform us in advance 48 hours&rsquo; notice of any upcoming news that you would like for us to publish specifically. When readers will click on the headlines, they will be taken to a link to your website. </span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">This content of yours may be protected by intellectual property laws. You own the intellectual property rights in any and all such content. Nothing in these Terms takes away the rights you have to your own content or news or magazines. You are free to share your content (except defamatory one) with anyone else, wherever you want.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">License:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&nbsp; However, to provide our services we need you to give us some legal permissions (known as a <em>&lsquo;license&rsquo;</em>) to use this content of yours. This is solely for the purposes of providing and improving our services.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Description of License:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Specifically, when you enter into an agreement with us for publishing your news headlines or magazines, you grant us a non-exclusive, transferable, sub-licensable, royalty-free, and worldwide license to host, use, publish, distribute, modify, copy, publicly perform or display, and translate your content on our Website. However, we might take down this content of yours if we, in good-faith, believe to be violative of our policies or any third-party rights. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Advertisements:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> We will not include your content in advertisements for the products and services of third parties to others without your separate consent. However, we have the right, without payment to you or others, to serve ads near your content and information. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You may share it with others:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Since you own your content and information and we only have non-exclusive rights to it, you may choose to make it available to others, at your sole discretion.</span></span></span></span></li>
</ol>

<p style="margin-left:96px; text-align:justify">&nbsp;</p>

<ol start="9">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">CONTENT OF NEWS AGENCIES</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">While using our Website and our services, you will encounter content, such as news headlines and/or magazines, which belongs to the third-party news agencies. Therefore, there is a likelihood that such information or content be inaccurate, incomplete, delayed, misleading, illegal, offensive or otherwise harmful. Recycling Market News generally does not review content of the news agencies, however, we reserve the right to do the same, and remove any content that violates any of our policies, in our sole discretion. </span></span></span></span></p>

<p style="margin-left:120px; text-align:justify">&nbsp;</p>

<ol start="10">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">LINKS TO THIRD-PARTY SITES AND ADS</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The Website might contain links to third-party websites, products and services. <em><u>For example, third-party payment gateway service providers, or links to third party news agencies.</u></em> Such third-party links are not under the control of Recycling Market News, and Recycling Market News is not responsible for any third-party links. Recycling Market News provides access to these third-party links only as a convenience to you, and does not review, approve, monitor, endorse, warrant, or make any representations with respect to third-party links. You shall use all third-party links at your own risk, and should apply a suitable level of caution and discretion in doing so. Whenever you click on such links, you are taken to such third-party website, and you get out of the jurisdiction of our Website. <u>Therefore, you shall be governed by the terms &amp; conditions, privacy policy and other policies of such third-party websites and we suggest that you read those policies.</u> <strong>In case of any damage due to such action of third-party links, Recycling Market News shall not be responsible.</strong></span></span></span></span></p>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="11">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">PRIVACY</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">In order to see what data we collect and how we use or store or share such data, please refer to the detailed <strong>Privacy Policy</strong> statement available on our Website.</span></span></span></span></p>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="12">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">PAYMENTS AND TAXES</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You agree to pay for the services that you avail from us, and you authorize us to charge your debit or credit card or process other means of payment for those payment. You shall be responsible to borne all the applicable taxes (wherever applicable). We employ the use of third-party service provider, namely, Stripe, for the purpose of facilitating payment and the completion of purchases. By submitting your information, you grant us the right to provide the information to Stripe subject to our Privacy Policy. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We reserve the right to modify the prices of our services, or modify or discontinue such services, at any time, at our sole discretion, without any prior notice. However, if you purchase our service for a particular price, that price and such service shall hold good for you until we have provided the same.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Upon registration as a news reader, you will receive 14-days free trial to try and explore our service. </span></span></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="13">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">LIMITATION OF LIABILITY</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">To the maximum extent permitted by applicable law, we DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FINANCIAL GAIN OR <span style="color:black">CAREER OR FITNESS FOR A PARTICULAR PURPOSE, TIMELINESS, ACCURACY, TITLE, AND NON-INFRINGEMENT about our services or prices of currencies &amp; commodities or the content posted by publishers/recyclers or the news headlines of the news agency posted by us on their direction. In no event shall Recycling Market News, or its owner(s), be liable to you or any third party for any lost profits, lost data, financial loss, trading loss, costs of procurement of substitute services, or any indirect, consequential, exemplary, incidental, special or punitive damages arising from or relating to these terms or our services or delay in update of the prices of currencies &amp; commodities, even if Recycling Market News has been advised of the possibility of such damages. Access to, and use of, the Website and Site and availing our services is at your own discretion and risk, and you will be solely responsible for any losses or damages resulting therefrom. The prices of the currencies, commodities and any other items displayed on the dashboard are only for informational purposes. Although, we take reasonable endeavors to ensure that their prices are updated every 10 minutes, we cannot however rule out the situations where these aren&rsquo;t updated on time for certain reasons or if these are inaccurate. Therefore, we disclaim all warranties to that respect, and will not be liable for any loss occurred by you due to your use such information for reason whatsoever. </span></span></span></span></span></p>

<p style="margin-left:72px; text-align:justify">&nbsp;</p>

<ol start="14">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">LEGAL ACTION</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">If you are found to be degrading, tarnishing, maligning the image, goodwill or reputation of <strong>Recycling Market News </strong>or its owners/directors, by spreading hate, insulting, false, fake reviews or engaging in mala fide actions against the above, strong legal actions will be taken immediately.</span></span></span></span></p>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="15">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">INDEMNITY</span></span></strong></span></span></li>
</ol>

<p style="margin-left:49px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You acknowledge to defend, indemnify and hold Recycling Market News, its owners/directors, and licensors (hereinafter referred to as<strong> &ldquo;Indemnified Party&rdquo;</strong>) harmless from and against any claim, disputes, fine, liability, demand or expense, including reasonable Lawyer&rsquo;s fees, made by a third party, relating to, or arising from:</span></span></span></span></p>

<ol style="list-style-type:lower-alpha">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Your violation of our rights or rights of other users, including without limitation to any right to privacy, publicity rights, defamation or intellectual property rights;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Your wrongful or improper use of our services, Site;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Your violation of any applicable laws, rules or regulations;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Your violation of these Terms or any other policy of ours as associated with our services;</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The indemnifications set forth above will survive the termination or expiration of these Terms and/or your use of our services.</span></span></span></span></li>
</ol>

<p style="text-align:justify">&nbsp;</p>

<ol start="16">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">GOVERNING LAW AND DISPUTE RESOLUTION</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-roman">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Governing Law: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">The Terms and any dispute arising from the same will be governed by applicable English laws.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Exclusive </span></span></strong><strong><span style="font-size:10.0pt"><span style="background-color:white"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Jurisdiction</span></span></span></strong><span style="font-size:10.0pt"><span style="background-color:white"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: All disputes must first be attempted to resolved amicably, failing which, such controversy, conflict or dispute shall be finally settled by bringing it before the appropriate courts situated in </span></span></span><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">London, England.</span></span></strong></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Disputes between users/news agencies of Recycling Market News or Publisher/Recyclers</span></span></strong><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You understand and acknowledge that Recycling Market News is an intermediary platform that publishes the news headlines of third-party news agencies, and we in no way are responsible for any of such news headline or content. Similarly, on our platform, anyone can become a news publisher/recycler and post news. Therefore, if you have any claim or dispute against a news agency or a specific piece of content hosted on our Site, you undertake to take it up directly with the concerned news agency or the publisher, as the case may be. Recycling Market News shall not mediate or resolve such disputes, and nor shall become a party to such disputes. <u>However, if you believe that any piece of content on our Site has violated these Terms, applicable law, or any other policy of Recycling Market News, you can file your complaint at info@recyclingmarketnews.com, and we will take necessary action in accordance to our policies and applicable law.</u></span></span></span></span></li>
</ol>

<p style="margin-left:120px; text-align:justify">&nbsp;</p>

<ol start="17">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">NOTICES</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">When you use the Website or send emails to Recycling Market News, you are communicating with us electronically. You consent to receive electronically any communications related to your use of this Website. Recycling Market News will communicate with you by email or by posting notices on this Website or through email. You agree that all agreements, notices, disclosures and other communications that are provided to you electronically satisfy any legal requirement that such communications be in writing. We may give notice by means of a general notice via electronic mail to your email address as available with us. If you want to give a notice to us, you can do so by dropping an electronic mail to</span></span> <strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">info@recyclingmarketnews.com</span></span></strong></span></span></p>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="18">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">MISCELLANEOUS</span></span></strong></span></span></li>
</ol>

<ol style="list-style-type:lower-roman">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Breach: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">In case of any breach or threatened breach to the provisions of these Terms, we reserve the right to suspend your account, and your access to our website, at our sole discretion, without any refund whatsoever.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Severability:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions of these Terms will continue in full force and effect.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Waiver:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Our failure to insist on or enforce strict performance of these Terms &amp; Conditions shall not be construed as a waiver by us of any provision or any right that we have to enforce these Terms and nor shall any course of conduct between us and you or any other party be deemed to modify any provision of these Terms.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Survival: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Notwithstanding any other provisions of these Terms &amp; Conditions, or any general legal principles to the contrary, any provision of these Terms &amp; Conditions that imposes or contemplates continuing obligations on either party shall survive the expiration or termination of these Terms &amp; Conditions, for any reason whatsoever.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">No Third-Party Beneficiaries: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Except as otherwise expressly provided in these Terms &amp; Conditions, there shall be no third-party beneficiaries to these Terms &amp; Conditions.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">No Assignment: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">You may not assign these Terms &amp; Conditions (or any rights, benefits or obligations hereunder) by operation of law or otherwise without the prior written consent of </span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Recycling Market News</span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">, which may be withheld at </span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Recycling Market News</span></span><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">&rsquo;s sole discretion. Any attempted assignment that does not comply with these Terms &amp; Conditions shall be null and void. </span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Entire Agreement:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> The <strong>Terms, Disclaimer,</strong></span></span><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Community Guidelines,</span></span></strong><strong> </strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">our<strong> Privacy Policy </strong>and <strong>Cookie Policy</strong>, together with any additional agreement executed between us, constitute the entire Agreement between Recycling Market News and you, relating to the subject matter hereof, and supersedes any prior understanding or agreements (whether oral or written) regarding the subject matter, and may not be amended or modified except in writing or by making such amendments or modifications available on our Website.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Force Majeure:</span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;"> Recycling Market News, its owner/director, and its agents will be excused from performance for any period during which, and to the extent that, such party or any subcontractor is prevented from performing any obligation or service, in whole or in part, as a result of causes beyond its reasonable control, and without its fault or negligence, including without limitation, acts of God, strikes, lockouts, riots, acts of terrorism or war, epidemics, communication line failures, power failures and government-imposed lockdowns or similar restrictions.</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Updates to these Terms: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We may add to or change or update these Terms at any time, from time to time, entirely at our own discretion, with or without any prior written notice. You are responsible for checking these Terms periodically. Your use of the Site after any amendments to the Terms shall constitute your acceptance to such amendments.</span></span></span></span></li>
</ol>

<p style="margin-left:96px; text-align:justify">&nbsp;</p>

<ol start="19">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Grievance Officer/Designated Representative</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="background-color:white"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">In the event you have any grievance regarding anything related to these <strong>Terms </strong>or <strong>Disclaimer</strong> or <strong>Privacy Policy</strong> or <strong>Cookie Policy</strong>, or with any of the content hosted on Recycling Market News, in that case you may freely write your concerns to the Grievance Officer/Designated Officer at:</span></span></span></span></span></p>

<ul>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Name: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Recycling Market News</span></span></span></span></li>
	<li style="text-align:justify"><span style="font-size:11pt">
	    <span style="font-family:Calibri,&quot;sans-serif&quot;">
	        <strong><span style="font-size:10.0pt">
	            <span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Email: </span>
	            </span>
	            </strong><a href="mailto:info@recyclingmarketnews.com" style="color:#0563c1; text-decoration:underline">
	                <span style="font-size:10.0pt">
	                    <span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">info@recyclingmarketnews.com</span></span></a>
	</span></li>
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Contact: </span></span></strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">001 905 670 2019</span></span></span></span></li>
</ul>

<p style="margin-left:48px; text-align:justify">&nbsp;</p>

<ol start="20">
	<li style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><strong><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Feedback and Information</span></span></strong></span></span></li>
</ol>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">We welcome your questions or comments regarding the Terms. You can write to us via email: </span></span><a href="mailto:info@recyclingmarketnews.com" style="color:#0563c1; text-decoration:underline"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">info@recyclingmarketnews.com</span></span></a> </span></span></p>

<p style="margin-left:48px; text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,&quot;sans-serif&quot;"><span style="font-size:10.0pt"><span style="font-family:&quot;Times New Roman&quot;,&quot;serif&quot;">Last updated on <strong>13<sup>th</sup> May 2022.</strong></span></span></span></span></p>

<p style="text-align:justify">&nbsp;</p>

<p style="text-align:justify">&nbsp;</p>

                                </div>
                            </div>
                        </div>
                        <!-- end page title -->

                        <div class="row">
                            <div class="col-xl-12">

                            </div>
                        </div>
  
                    </div> <!-- container-fluid -->
                </div>
                <!-- End Page-content -->
<?php $__env->stopSection(); ?>



<?php echo $__env->make('dashboard.layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/wu6wt82f25ae/public_html/recyclingmarketnews.com/resources/views/dashboard/terms-conditions.blade.php ENDPATH**/ ?>